package Ex_19_OOPs_Part2._5_Super_keyword;

public class Lab175_Superkeyword_intro {
    /*
   1. super keyword is used to calling the parents class constructor/variable/method.
   2. this keywrd is used to call the current class variable/method/constructor.
   3.if the child class doesn't contain  this keyword and super keyword then compiler generate the  super keyword with
   0 args cons calling.
     */
}
/*
class parent
{
   parent()
  {
   sout("parent class 0 args cons")
  }
}
 class child extends parents()
 {
   child()
   {
    super() :it is generated by compiler..

    sout("child class 0 args cons")
   }

   psvm(String[] args)
    {
      new child();
    }
 }

 */
